#!/bin/bash
### BEGIN INIT INFO
# Provides:          detection
# Required-Start:    $all
# Required-Stop:     
# Default-Start:     5
# Default-Stop:      0 1 6
# Short-Description: Fall Detection
### END INIT INFO
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:$PATH

#DESC="Fall Detection"
#PIDFILE=/var/run/detection.pid
#SCRIPTNAME=/etc/init.d/detection

case "$1" in
  start)
    sleep 60
    printf "%-50s" "Starting fall detection..."
    cd /home/pi/detection
    python3 fall_detection.py
    ;;
  stop)
    printf "%-50s" "Stopping ibeacon..."
    pkill -9 -f fall_detection.py
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac
#sudo update-rc.d -f detection defaults