#!/bin/sh
BLUETOOTH_DEVICE=hci0
UUID="63 6F 3F 8F 64 91 4B EE 95 F7 D8 CC 64 A8 63 B5"
MAJOR="00 00"
MINOR="00 00"
POWER="C8 00"
echo "Launching virtual iBeacon..."
sudo hciconfig $BLUETOOTH_DEVICE up
sudo hciconfig $BLUETOOTH_DEVICE noleadv
sudo hciconfig $BLUETOOTH_DEVICE leadv 0
sudo hcitool -i hci0 cmd 0x08 0x0008 1e 02 01 1a 1a ff 4c 00 02 15 $UUID $MAJOR $MINOR $POWER
echo "Complete"
